In [3]:
with open('./drive/Mydrive/ReadME,md','w') as f:
  data = f.write = f.write('**반가워')

FileNotFoundError: [Errno 2] No such file or directory: './drive/Mydrive/ReadME,md'

In [2]:
!pwd

/content


# 넘파이(numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열 안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

In [10]:
#pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry)
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[3])
print(narry[2:4]) # <= x <

[0 1 2 3 4]
1
(5,)
5
3
[2 3]


In [16]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b']) # 숫자와 문자가 함께 들어가면 모두 str 처리를 해버린다,
narr3 = np.array([1,2,'a','b'], dtype = 'str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' 'a' 'b'] <U1


In [80]:
narr4 = np.zeros((2,2),dtype = 'int64')
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),'number')
narr8 =  np.eye(3)
narr9 = np.linspace(0,100,5, endpoint=False, dtype='int64')
narr10 = np.arange(0,100,20)
print(narr4, narr4.ndim, narr4.dtype, narr4.shape, narr4.size, type(narr4))
print(narr5, narr5.ndim, narr5.dtype, narr5.shape, narr5.size, type(narr5))
print(narr6, narr6.ndim, narr6.dtype, narr6.shape, narr6.size, type(narr6))
print(narr7, narr7.ndim, narr7.dtype, narr7.shape, narr7.size, type(narr7))
print(narr8, narr8.ndim, narr8.dtype, narr8.shape, narr8.size, type(narr8))
print(narr9, narr9.ndim, narr9.dtype, narr9.shape, narr9.size, type(narr9))
print(narr10, narr10.ndim, narr10.dtype, narr10.shape, narr10.size, type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


In [28]:
arr1 = np.array([[0,0],[0,0]])
print(arr1, arr1.ndim, arr1.dtype, arr1, arr1.size, type(arr1))

[[0 0]
 [0 0]] 2 int64 [[0 0]
 [0 0]] 4 <class 'numpy.ndarray'>


# 2차원 배열

In [37]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(20)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2 = np.array([[1,2,3,4,5,6,7,8,9]])
print(arr2, arr2.ndim, arr2.dtype, arr2, arr2.size, type(arr2))

In [53]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim,'/ 데이터타입:', arr2.dtype,'/형태:', arr2.shape, '/크기:', arr2.size, type(arr2),arr2)
print('차원:',arr3.ndim,'/ 데이터타입:', arr3.dtype,'/형태:', arr3.shape, '/크기:', arr3.size, type(arr3),arr3)
print('차원:',arr4.ndim,'/ 데이터타입:', arr4.dtype,'/형태:', arr4.shape, '/크기:', arr4.size, type(arr4),arr4)
print('차원:',arr5.ndim,'/ 데이터타입:', arr5.dtype,'/형태:', arr5.shape, '/크기:', arr5.size, type(arr5),arr5)
print('차원:',arr6.ndim,'/ 데이터타입:', arr6.dtype,'/형태:', arr6.shape, '/크기:', arr6.size, type(arr6),arr6)

차원: 2 / 데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 / 데이터타입: int64 /형태: (3, 3) /크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 / 데이터타입: int64 /형태: (2, 5) /크기: 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 / 데이터타입: int64 /형태: (5, 2) /크기: 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 / 데이터타입: int64 /형태: (3, 3, 3) /크기: 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [96]:
arr3 = np.arange(1,22).reshape(3,7)
arr4 = np.arange(1,8).reshape(7,1)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,13).reshape(3,4,1)

print(arr3)
print('='*30)
print(arr4)
print('='*30)
print(arr5)
print('='*30)
print(arr3)
print('='*30)
print(arr6)
print(arr3[1:3,2:4])
print(arr3[1:3,2:5])
print(arr3[arr3 > 12])
print(arr3 % 2 == 0)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
[[10 11]
 [17 18]]
[[10 11 12]
 [17 18 19]]
[13 14 15 16 17 18 19 20 21]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [97]:
# np 배열 연산 // shape가 같을 경우 원소별 연산이 가능
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [-5 -5 -5 -5 -5]
곱셈: [ 6 14 24 36 50]
나눗셈: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [98]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[11 12 13 14 15]


In [102]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
print(br1)
print(br2)
# 스칼라와 연산
print("==============")
print(br1+3)
print(br1*3)
# 2D와 1D의 연산
print("==============")
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[11 22 33]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [105]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff)
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [1]:
from google import genai

client = genai.Client(api_key="AIzaSyB_eerncLSXPC1eSYf2sEoKNlF03s35szA")
response = client.models.generate_content(
    model="gemini-2.0-flash", contents="Explain how AI works"
)
print(response.text)

ModuleNotFoundError: No module named 'google'

In [2]:
!pip install google

## Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [6]:
# randomint
import numpy as np
x = np.random.randint(1,100,size=(3,3,3))
x

array([[[87, 17, 32],
        [45, 40, 58],
        [23, 92, 59]],

       [[49, 58, 95],
        [49, 99, 73],
        [43, 66, 10]],

       [[51, 51, 60],
        [12, 49, 97],
        [96, 25, 85]]], dtype=int32)

In [12]:
print('평균값: ', np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값:  56.333333333333336 표준편차: 26.60409325231322 최소값: 10 최대값: 99


In [14]:
print(len(x.flatten()))

27


In [22]:
import numpy as np
y = np.array([1,10,2,3,4,12,3,5,0,3,4,5,6,4,5,4,50,2,3,2,3,2,3,2,3,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
26
